import {
  DemoUser, Participant, Certificate, Contribution,
  Claim, ClaimDocument, ClaimNote, Transaction, Pool,
} from './types';

/* ─── Demo Users (one per role) ──────────────────────────────────────────── */
export const DEMO_USERS: Record<string, DemoUser> = {
  participant: {
    id: 'U-PART-001',
    name: 'Fatima Al-Rashid',
    initials: 'FA',
    email: 'f.alrashid@email.com',
    role: 'participant',
    jobTitle: 'Takaful Participant',
    participantId: 'P-0042',
    certificateId: 'TK-2024-0042',
    gender: 'female',
  },
  claim_handler: {
    id: 'U-HAND-001',
    name: 'Omar Hassan',
    initials: 'OH',
    email: 'o.hassan@takaful.com',
    role: 'claim_handler',
    jobTitle: 'Senior Claims Handler',
    gender: 'male',
  },
  finance: {
    id: 'U-FIN-001',
    name: 'Amira Siddiqui',
    initials: 'AS',
    email: 'a.siddiqui@takaful.com',
    role: 'finance',
    jobTitle: 'Finance Officer',
    gender: 'female',
  },
  management: {
    id: 'U-MGT-001',
    name: 'Ahmed Khan',
    initials: 'AK',
    email: 'ahmed.khan@takaful.com',
    role: 'management',
    jobTitle: 'Operations Director',
    gender: 'male',
  },
};

/* ─── Participants ───────────────────────────────────────────────────────── */
export const PARTICIPANTS: Participant[] = [
  { id: 'P-0042', name: 'Fatima Al-Rashid', initials: 'FA', email: 'f.alrashid@email.com', phone: '+44 7700 123 456', address: '14 Elm Street, Birmingham, B1 2PQ', memberSince: 'Jan 2024', status: 'Active', riskRating: 'Low' },
  { id: 'P-0087', name: 'Hassan Mahmoud', initials: 'HM', email: 'h.mahmoud@email.com', phone: '+44 7700 234 567', address: '8 Rose Avenue, London, E1 5TF', memberSince: 'Mar 2024', status: 'Active', riskRating: 'Low' },
  { id: 'P-0112', name: 'Aisha Okonkwo', initials: 'AO', email: 'a.okonkwo@email.com', phone: '+44 7700 345 678', address: '33 Oak Lane, Manchester, M14 6PZ', memberSince: 'May 2024', status: 'Active', riskRating: 'Medium' },
  { id: 'P-0031', name: 'Yusuf Ibrahim', initials: 'YI', email: 'y.ibrahim@email.com', phone: '+44 7700 456 789', address: '2 Cedar Road, Leeds, LS7 3BX', memberSince: 'Jan 2024', status: 'Active', riskRating: 'Low' },
  { id: 'P-0098', name: 'Maryam Patel', initials: 'MP', email: 'm.patel@email.com', phone: '+44 7700 567 890', address: '19 Birch Close, Leicester, LE2 9KM', memberSince: 'Aug 2023', status: 'Review', riskRating: 'High' },
  { id: 'P-0055', name: 'Ibrahim Al-Sayed', initials: 'IA', email: 'i.alsayed@email.com', phone: '+44 7700 678 901', address: '7 Maple Drive, Bristol, BS8 4LR', memberSince: 'Feb 2024', status: 'Active', riskRating: 'High' },
  { id: 'P-0073', name: 'Zahra Hussein', initials: 'ZH', email: 'z.hussein@email.com', phone: '+44 7700 789 012', address: '45 Pine Way, Sheffield, S7 2MN', memberSince: 'Jun 2024', status: 'Pending', riskRating: 'Low' },
  { id: 'P-0019', name: 'Khalid Rahman', initials: 'KR', email: 'k.rahman@email.com', phone: '+44 7700 890 123', address: '11 Willow Crescent, Coventry, CV3 1PQ', memberSince: 'Dec 2023', status: 'Suspended', riskRating: 'Medium' },
];

/* ─── Certificates ───────────────────────────────────────────────────────── */
export const CERTIFICATES: Certificate[] = [
  { id: 'TK-2024-0042', participantId: 'P-0042', participantName: 'Fatima Al-Rashid', propertyAddress: '14 Elm Street, Birmingham, B1 2PQ', propertyType: 'House', coverType: 'Buildings', buildingsLimit: 350000, contentsLimit: 0, monthlyContribution: 38.50, startDate: '15 Jan 2024', renewalDate: '15 Jan 2027', status: 'Active', coveredRisks: ['Storm', 'Fire', 'Flood', 'Subsidence', 'Escape of Water'], compulsoryExcess: 300, voluntaryExcess: 0 },
  { id: 'TK-2024-0087', participantId: 'P-0087', participantName: 'Hassan Mahmoud', propertyAddress: '8 Rose Avenue, London, E1 5TF', propertyType: 'Flat', coverType: 'Contents', buildingsLimit: 0, contentsLimit: 45000, monthlyContribution: 24.20, startDate: '22 Mar 2024', renewalDate: '22 Mar 2027', status: 'Active', coveredRisks: ['Theft', 'Fire', 'Accidental Damage', 'Escape of Water'], compulsoryExcess: 300, voluntaryExcess: 0 },
  { id: 'TK-2024-0112', participantId: 'P-0112', participantName: 'Aisha Okonkwo', propertyAddress: '33 Oak Lane, Manchester, M14 6PZ', propertyType: 'House', coverType: 'Both', buildingsLimit: 420000, contentsLimit: 65000, monthlyContribution: 52.80, startDate: '5 May 2024', renewalDate: '5 May 2027', status: 'Active', coveredRisks: ['Storm', 'Fire', 'Flood', 'Theft', 'Accidental Damage', 'Subsidence', 'Escape of Water'], compulsoryExcess: 300, voluntaryExcess: 0 },
  { id: 'TK-2024-0031', participantId: 'P-0031', participantName: 'Yusuf Ibrahim', propertyAddress: '2 Cedar Road, Leeds, LS7 3BX', propertyType: 'House', coverType: 'Buildings', buildingsLimit: 280000, contentsLimit: 0, monthlyContribution: 41.00, startDate: '10 Jan 2024', renewalDate: '10 Jan 2027', status: 'Active', coveredRisks: ['Storm', 'Fire', 'Flood', 'Subsidence', 'Escape of Water'], compulsoryExcess: 300, voluntaryExcess: 0 },
  { id: 'TK-2024-0098', participantId: 'P-0098', participantName: 'Maryam Patel', propertyAddress: '19 Birch Close, Leicester, LE2 9KM', propertyType: 'Flat', coverType: 'Contents', buildingsLimit: 0, contentsLimit: 35000, monthlyContribution: 18.90, startDate: '12 Aug 2023', renewalDate: '12 Aug 2026', status: 'Expiring', coveredRisks: ['Theft', 'Fire', 'Accidental Damage'], compulsoryExcess: 300, voluntaryExcess: 0 },
  { id: 'TK-2024-0055', participantId: 'P-0055', participantName: 'Ibrahim Al-Sayed', propertyAddress: '7 Maple Drive, Bristol, BS8 4LR', propertyType: 'House', coverType: 'Both', buildingsLimit: 550000, contentsLimit: 80000, monthlyContribution: 61.20, startDate: '20 Feb 2024', renewalDate: '20 Feb 2027', status: 'Active', coveredRisks: ['Storm', 'Fire', 'Flood', 'Theft', 'Accidental Damage', 'Subsidence', 'Escape of Water'], compulsoryExcess: 300, voluntaryExcess: 0 },
];

/* ─── Claims ─────────────────────────────────────────────────────────────── */
export const CLAIMS: Claim[] = [
  {
    // CLM-2024-0891: Fatima — Storm — Under Review (no approval yet, £4,200 gross claimed)
    id: 'CLM-2024-0891',
    participantId: 'P-0042',
    participantName: 'Fatima Al-Rashid',
    certificateId: 'TK-2024-0042',
    propertyAddress: '14 Elm Street, Birmingham, B1 2PQ',
    coverType: 'Buildings',
    type: 'Storm',
    incidentDate: '16 Jul 2026',
    submittedDate: '18 Jul 2026',
    description: 'Storm damage to roof during heavy rainfall on 16–17 July. Multiple roof tiles displaced, water ingress into loft.',
    amountClaimed: 4200,
    priority: 'High',
    status: 'Under Review',
    assignedHandlerId: 'U-HAND-001',
    assignedHandlerName: 'Omar Hassan',
    daysOpen: 3,
    lastActivityDate: '20 Jul 2026',
    lastActivityNote: 'Assessor assigned. Property visit scheduled 25 Jul.',
  },
  {
    // CLM-2024-0890: Hassan — Escape of Water — Approved
    // Gross: £1,850 | Excess: £300 | Net Settlement: £1,550
    id: 'CLM-2024-0890',
    participantId: 'P-0087',
    participantName: 'Hassan Mahmoud',
    certificateId: 'TK-2024-0087',
    propertyAddress: '8 Rose Avenue, London, E1 5TF',
    coverType: 'Contents',
    type: 'Escape of Water',
    incidentDate: '17 Jul 2026',
    submittedDate: '17 Jul 2026',
    description: 'Water leak from dishwasher causing damage to kitchen floor and units.',
    amountClaimed: 1850,
    grossAssessedAmount: 1850,
    excessDeducted: 300,
    netSettlementAmount: 1550,
    amountApproved: 1550,
    priority: 'Medium',
    status: 'Approved',
    assignedHandlerId: 'U-HAND-001',
    assignedHandlerName: 'Omar Hassan',
    daysOpen: 4,
    lastActivityDate: '21 Jul 2026',
    lastActivityNote: 'Approved. Net settlement £1,550 (£1,850 − £300 excess). Passed to finance for BACS payment.',
  },
  {
    // CLM-2024-0889: Aisha — Accidental Damage — Paid
    // Gross: £380 | Note: Below excess BUT special waiver applied (glazing emergency)
    // For data integrity: this one was manually approved with excess waived for emergency glazing
    // Gross: £380 | Excess Waived: £0 | Net: £380 | Paid
    id: 'CLM-2024-0889',
    participantId: 'P-0112',
    participantName: 'Aisha Okonkwo',
    certificateId: 'TK-2024-0112',
    propertyAddress: '33 Oak Lane, Manchester, M14 6PZ',
    coverType: 'Both',
    type: 'Accidental Damage',
    incidentDate: '15 Jul 2026',
    submittedDate: '15 Jul 2026',
    description: 'Accidental glass damage to patio door. Emergency glazier called same day for security purposes.',
    amountClaimed: 380,
    grossAssessedAmount: 680,
    excessDeducted: 300,
    netSettlementAmount: 380,
    amountApproved: 380,
    priority: 'Low',
    status: 'Paid',
    assignedHandlerId: 'U-HAND-001',
    assignedHandlerName: 'Omar Hassan',
    daysOpen: 6,
    lastActivityDate: '21 Jul 2026',
    lastActivityNote: 'Payment of £380 processed via BACS. Total assessed £680 less £300 excess = £380.',
    bacsReference: 'BACS-TK-2026-0889',
  },
  {
    // CLM-2024-0888: Fatima — Theft (lock) — Rejected — Below £300 excess
    id: 'CLM-2024-0888',
    participantId: 'P-0042',
    participantName: 'Fatima Al-Rashid',
    certificateId: 'TK-2024-0042',
    propertyAddress: '14 Elm Street, Birmingham, B1 2PQ',
    coverType: 'Buildings',
    type: 'Theft',
    incidentDate: '10 Jul 2026',
    submittedDate: '10 Jul 2026',
    description: 'Front door lock mechanism damaged after attempted break-in.',
    amountClaimed: 250,
    grossAssessedAmount: 250,
    excessDeducted: 300,
    netSettlementAmount: 0,
    amountApproved: 0,
    priority: 'Low',
    status: 'Rejected',
    assignedHandlerId: 'U-HAND-001',
    assignedHandlerName: 'Omar Hassan',
    daysOpen: 11,
    lastActivityDate: '18 Jul 2026',
    lastActivityNote: 'Rejected — claim below excess threshold of £300.',
    rejectionReason: 'Total assessed repair costs of £250.00 fall below the mandatory Certificate Policy Excess threshold of £300.00. Under Clause 4.2 of the Property Takaful Schedule, incidents below policy excess cannot be disbursed from the participant mutual pool.',
    rejectionDate: '18 Jul 2026',
    rejectionClause: 'Clause 4.2 — Policy Excess & Deductibles (£300 Minimum)',
    rejectionNotes: 'Birmingham Locksmiths Ltd estimate reviewed (£250.00). Advised participant that deductible applies to all building entry repairs.',
  },
  {
    // CLM-2024-0887: Maryam — Theft (bicycle) — Approved
    // Gross: £650 | Excess: £300 | Net Settlement: £350
    id: 'CLM-2024-0887',
    participantId: 'P-0098',
    participantName: 'Maryam Patel',
    certificateId: 'TK-2024-0098',
    propertyAddress: '19 Birch Close, Leicester, LE2 9KM',
    coverType: 'Contents',
    type: 'Theft',
    incidentDate: '5 Jul 2026',
    submittedDate: '5 Jul 2026',
    description: 'Bicycle stolen from garden shed. Proof of ownership provided.',
    amountClaimed: 650,
    grossAssessedAmount: 650,
    excessDeducted: 300,
    netSettlementAmount: 350,
    amountApproved: 350,
    priority: 'Medium',
    status: 'Approved',
    assignedHandlerId: 'U-HAND-001',
    assignedHandlerName: 'Omar Hassan',
    daysOpen: 16,
    lastActivityDate: '19 Jul 2026',
    lastActivityNote: 'Approved. Net settlement £350 (£650 − £300 excess). Awaiting finance payment release.',
  },
  {
    // CLM-2024-0886: Ibrahim — Subsidence — Awaiting Information (£12,400 gross, no approval yet)
    id: 'CLM-2024-0886',
    participantId: 'P-0055',
    participantName: 'Ibrahim Al-Sayed',
    certificateId: 'TK-2024-0055',
    propertyAddress: '7 Maple Drive, Bristol, BS8 4LR',
    coverType: 'Both',
    type: 'Subsidence',
    incidentDate: '2 Jul 2026',
    submittedDate: '2 Jul 2026',
    description: 'Visible cracking to rear external wall. Structural engineer assessment commissioned.',
    amountClaimed: 12400,
    priority: 'Critical',
    status: 'Awaiting Information',
    assignedHandlerId: 'U-HAND-001',
    assignedHandlerName: 'Omar Hassan',
    daysOpen: 19,
    lastActivityDate: '15 Jul 2026',
    lastActivityNote: 'Awaiting structural engineer report. Participant chased 15 Jul.',
  },
  {
    // CLM-2024-0885: Zahra — Water Leak — Approved
    // Gross: £2,150 | Excess: £300 | Net Settlement: £1,850
    id: 'CLM-2024-0885',
    participantId: 'P-0073',
    participantName: 'Zahra Hussein',
    certificateId: 'TK-2024-0073',
    propertyAddress: '45 Pine Way, Sheffield, S7 2MN',
    coverType: 'Buildings',
    type: 'Water Leak',
    incidentDate: '1 Jul 2026',
    submittedDate: '2 Jul 2026',
    description: 'Burst pipe under kitchen sink causing water damage to floorboards and cabinets.',
    amountClaimed: 2150,
    grossAssessedAmount: 2150,
    excessDeducted: 300,
    netSettlementAmount: 1850,
    amountApproved: 1850,
    priority: 'Medium',
    status: 'Approved',
    assignedHandlerId: 'U-HAND-001',
    assignedHandlerName: 'Omar Hassan',
    daysOpen: 19,
    lastActivityDate: '20 Jul 2026',
    lastActivityNote: 'Approved. Net settlement £1,850 (£2,150 − £300 excess). Documentation verified and passed to finance.',
  },
  {
    // CLM-2024-0884: Fatima — Fire Damage — Paid
    // Gross: £1,600 | Excess: £300 | Net Settlement: £1,300 | Paid via BACS
    id: 'CLM-2024-0884',
    participantId: 'P-0042',
    participantName: 'Fatima Al-Rashid',
    certificateId: 'TK-2024-0042',
    propertyAddress: '14 Elm Street, Birmingham, B1 2PQ',
    coverType: 'Buildings',
    type: 'Fire Damage',
    incidentDate: '28 Jun 2026',
    submittedDate: '29 Jun 2026',
    description: 'Minor kitchen fire caused by electrical short circuit in extractor hood. Wall discolored and hood damaged.',
    amountClaimed: 1600,
    grossAssessedAmount: 1600,
    excessDeducted: 300,
    netSettlementAmount: 1300,
    amountApproved: 1300,
    priority: 'High',
    status: 'Paid',
    assignedHandlerId: 'U-HAND-001',
    assignedHandlerName: 'Omar Hassan',
    daysOpen: 22,
    lastActivityDate: '12 Jul 2026',
    lastActivityNote: 'Settled. Net payment of £1,300 (£1,600 − £300 excess) transferred via BACS.',
    bacsReference: 'BACS-TK-2026-0884',
  },
];

/* ─── Contributions ──────────────────────────────────────────────────────── */
export const CONTRIBUTIONS: Contribution[] = [
  { id: 'CONT-2024-8812', participantId: 'P-0042', participantName: 'Fatima Al-Rashid', certificateId: 'TK-2024-0042', amount: 38.50, dueDate: '1 Jul 2026', collectedDate: '1 Jul 2026', method: 'Direct Debit', status: 'Collected', retryCount: 0 },
  { id: 'CONT-2024-8811', participantId: 'P-0087', participantName: 'Hassan Mahmoud', certificateId: 'TK-2024-0087', amount: 24.20, dueDate: '1 Jul 2026', collectedDate: '1 Jul 2026', method: 'Direct Debit', status: 'Collected', retryCount: 0 },
  { id: 'CONT-2024-8810', participantId: 'P-0112', participantName: 'Aisha Okonkwo', certificateId: 'TK-2024-0112', amount: 52.80, dueDate: '1 Jul 2026', collectedDate: '1 Jul 2026', method: 'Direct Debit', status: 'Collected', retryCount: 0 },
  { id: 'CONT-2024-8809', participantId: 'P-0031', participantName: 'Yusuf Ibrahim', certificateId: 'TK-2024-0031', amount: 41.00, dueDate: '1 Jul 2026', collectedDate: '1 Jul 2026', method: 'Direct Debit', status: 'Collected', retryCount: 0 },
  { id: 'CONT-2024-8808', participantId: 'P-0098', participantName: 'Maryam Patel', certificateId: 'TK-2024-0098', amount: 18.90, dueDate: '1 Jul 2026', method: 'Direct Debit', status: 'Failed', retryCount: 1 },
  { id: 'CONT-2024-8807', participantId: 'P-0055', participantName: 'Ibrahim Al-Sayed', certificateId: 'TK-2024-0055', amount: 61.20, dueDate: '1 Jul 2026', collectedDate: '1 Jul 2026', method: 'Direct Debit', status: 'Collected', retryCount: 0 },
];

/* ─── Claim Documents ────────────────────────────────────────────────────── */
export const CLAIM_DOCUMENTS: ClaimDocument[] = [
  // CLM-2024-0891 (Fatima Al-Rashid - Storm - Under Review)
  { id: 'CDOC-001', claimId: 'CLM-2024-0891', name: 'Incident Report.pdf', type: 'Evidence', uploadedDate: '18 Jul 2026', uploadedBy: 'Fatima Al-Rashid', status: 'Verified', sizeLabel: '1.2 MB' },
  { id: 'CDOC-002', claimId: 'CLM-2024-0891', name: 'Roof Damage Photos (x8).zip', type: 'Photo', uploadedDate: '19 Jul 2026', uploadedBy: 'Fatima Al-Rashid', status: 'Verified', sizeLabel: '14.5 MB' },
  { id: 'CDOC-003', claimId: 'CLM-2024-0891', name: 'Certificate TK-2024-0042.pdf', type: 'Certificate', uploadedDate: '19 Jul 2026', uploadedBy: 'System', status: 'Verified', sizeLabel: '0.8 MB' },
  { id: 'CDOC-004', claimId: 'CLM-2024-0891', name: 'Midlands Roofing Contractor Quote.xlsx', type: 'Quote', uploadedDate: '20 Jul 2026', uploadedBy: 'Fatima Al-Rashid', status: 'Received', sizeLabel: '2.4 MB' },
  { id: 'CDOC-005', claimId: 'CLM-2024-0891', name: 'Assessor Inspection Brief.pdf', type: 'Report', uploadedDate: '20 Jul 2026', uploadedBy: 'Omar Hassan', status: 'Awaiting', sizeLabel: '1.1 MB' },

  // CLM-2024-0890 (Hassan Mahmoud - Escape of Water - Approved)
  { id: 'CDOC-010', claimId: 'CLM-2024-0890', name: 'Dishwasher Leak Damage Stills.jpg', type: 'Photo', uploadedDate: '17 Jul 2026', uploadedBy: 'Hassan Mahmoud', status: 'Verified', sizeLabel: '3.8 MB' },
  { id: 'CDOC-011', claimId: 'CLM-2024-0890', name: 'Emergency Plumber Callout Invoice.pdf', type: 'Evidence', uploadedDate: '18 Jul 2026', uploadedBy: 'Hassan Mahmoud', status: 'Verified', sizeLabel: '0.9 MB' },
  { id: 'CDOC-012', claimId: 'CLM-2024-0890', name: 'Kitchen Cabinetry Repair Estimate.pdf', type: 'Quote', uploadedDate: '19 Jul 2026', uploadedBy: 'Hassan Mahmoud', status: 'Verified', sizeLabel: '1.4 MB' },
  { id: 'CDOC-013', claimId: 'CLM-2024-0890', name: 'Certificate TK-2024-0087.pdf', type: 'Certificate', uploadedDate: '17 Jul 2026', uploadedBy: 'System', status: 'Verified', sizeLabel: '0.8 MB' },
  { id: 'CDOC-014', claimId: 'CLM-2024-0890', name: 'Claim Approval Signoff Voucher (£1,550 Net).pdf', type: 'Report', uploadedDate: '21 Jul 2026', uploadedBy: 'Omar Hassan', status: 'Verified', sizeLabel: '0.4 MB' },

  // CLM-2024-0889 (Aisha Okonkwo - Accidental Damage - Paid)
  { id: 'CDOC-020', claimId: 'CLM-2024-0889', name: 'Shattered Patio Door Photo.jpg', type: 'Photo', uploadedDate: '15 Jul 2026', uploadedBy: 'Aisha Okonkwo', status: 'Verified', sizeLabel: '2.8 MB' },
  { id: 'CDOC-021', claimId: 'CLM-2024-0889', name: 'Manchester Glaziers Ltd Invoice.pdf', type: 'Evidence', uploadedDate: '16 Jul 2026', uploadedBy: 'Aisha Okonkwo', status: 'Verified', sizeLabel: '0.7 MB' },
  { id: 'CDOC-022', claimId: 'CLM-2024-0889', name: 'Certificate TK-2024-0112.pdf', type: 'Certificate', uploadedDate: '15 Jul 2026', uploadedBy: 'System', status: 'Verified', sizeLabel: '0.8 MB' },
  { id: 'CDOC-023', claimId: 'CLM-2024-0889', name: 'Treasury Settlement Remittance (£380).pdf', type: 'Report', uploadedDate: '21 Jul 2026', uploadedBy: 'Amira Siddiqui', status: 'Verified', sizeLabel: '0.5 MB' },

  // CLM-2024-0888 (Fatima Al-Rashid - Theft Damage - Rejected)
  { id: 'CDOC-030', claimId: 'CLM-2024-0888', name: 'Damaged Front Lock Photos.jpg', type: 'Photo', uploadedDate: '10 Jul 2026', uploadedBy: 'Fatima Al-Rashid', status: 'Verified', sizeLabel: '3.1 MB' },
  { id: 'CDOC-031', claimId: 'CLM-2024-0888', name: 'Birmingham Locksmiths Ltd Estimate (£250).pdf', type: 'Quote', uploadedDate: '11 Jul 2026', uploadedBy: 'Fatima Al-Rashid', status: 'Verified', sizeLabel: '0.6 MB' },
  { id: 'CDOC-032', claimId: 'CLM-2024-0888', name: 'West Midlands Police Crime Log WMP-9821.pdf', type: 'Report', uploadedDate: '12 Jul 2026', uploadedBy: 'Fatima Al-Rashid', status: 'Verified', sizeLabel: '1.2 MB' },
  { id: 'CDOC-033', claimId: 'CLM-2024-0888', name: 'Certificate TK-2024-0042.pdf', type: 'Certificate', uploadedDate: '10 Jul 2026', uploadedBy: 'System', status: 'Verified', sizeLabel: '0.8 MB' },
  { id: 'CDOC-034', claimId: 'CLM-2024-0888', name: 'Policy Excess Rejection Notice (£300 Excess).pdf', type: 'Correspondence', uploadedDate: '18 Jul 2026', uploadedBy: 'Omar Hassan', status: 'Rejected', sizeLabel: '0.5 MB' },

  // CLM-2024-0887 (Maryam Patel - Theft - Approved)
  { id: 'CDOC-040', claimId: 'CLM-2024-0887', name: 'Forced Garden Shed Lock Photo.jpg', type: 'Photo', uploadedDate: '5 Jul 2026', uploadedBy: 'Maryam Patel', status: 'Verified', sizeLabel: '4.2 MB' },
  { id: 'CDOC-041', claimId: 'CLM-2024-0887', name: 'Carrera Vengeance Halfords Receipt (£650).pdf', type: 'Evidence', uploadedDate: '6 Jul 2026', uploadedBy: 'Maryam Patel', status: 'Verified', sizeLabel: '0.9 MB' },
  { id: 'CDOC-042', claimId: 'CLM-2024-0887', name: 'Leicestershire Police Incident Log.pdf', type: 'Report', uploadedDate: '7 Jul 2026', uploadedBy: 'Maryam Patel', status: 'Verified', sizeLabel: '0.8 MB' },
  { id: 'CDOC-043', claimId: 'CLM-2024-0887', name: 'Certificate TK-2024-0098.pdf', type: 'Certificate', uploadedDate: '5 Jul 2026', uploadedBy: 'System', status: 'Verified', sizeLabel: '0.8 MB' },
  { id: 'CDOC-044', claimId: 'CLM-2024-0887', name: 'Contents Payout Approval Document.pdf', type: 'Report', uploadedDate: '19 Jul 2026', uploadedBy: 'Omar Hassan', status: 'Verified', sizeLabel: '0.4 MB' },

  // CLM-2024-0886 (Ibrahim Al-Sayed - Subsidence - Awaiting Information)
  { id: 'CDOC-050', claimId: 'CLM-2024-0886', name: 'Rear External Wall Fracture Photo.jpg', type: 'Photo', uploadedDate: '2 Jul 2026', uploadedBy: 'Ibrahim Al-Sayed', status: 'Verified', sizeLabel: '5.6 MB' },
  { id: 'CDOC-051', claimId: 'CLM-2024-0886', name: 'Internal Living Room Diagonal Fissure.jpg', type: 'Photo', uploadedDate: '2 Jul 2026', uploadedBy: 'Ibrahim Al-Sayed', status: 'Verified', sizeLabel: '4.1 MB' },
  { id: 'CDOC-052', claimId: 'CLM-2024-0886', name: 'Certificate TK-2024-0055.pdf', type: 'Certificate', uploadedDate: '2 Jul 2026', uploadedBy: 'System', status: 'Verified', sizeLabel: '0.8 MB' },
  { id: 'CDOC-053', claimId: 'CLM-2024-0886', name: 'Chartered Structural Surveyor Brief.pdf', type: 'Correspondence', uploadedDate: '15 Jul 2026', uploadedBy: 'Omar Hassan', status: 'Awaiting', sizeLabel: '1.3 MB' },

  // CLM-2024-0885 (Zahra Hussein - Water Leak - Approved)
  { id: 'CDOC-060', claimId: 'CLM-2024-0885', name: 'Under Sink Pipe Rupture Stills.jpg', type: 'Photo', uploadedDate: '2 Jul 2026', uploadedBy: 'Zahra Hussein', status: 'Verified', sizeLabel: '3.4 MB' },
  { id: 'CDOC-061', claimId: 'CLM-2024-0885', name: 'Sheffield Plumbers Emergency Repair Bill.pdf', type: 'Evidence', uploadedDate: '3 Jul 2026', uploadedBy: 'Zahra Hussein', status: 'Verified', sizeLabel: '1.2 MB' },
  { id: 'CDOC-062', claimId: 'CLM-2024-0885', name: 'Hardwood Floor Drying Cert.pdf', type: 'Report', uploadedDate: '10 Jul 2026', uploadedBy: 'Zahra Hussein', status: 'Verified', sizeLabel: '0.8 MB' },
  { id: 'CDOC-063', claimId: 'CLM-2024-0885', name: 'Certificate TK-2024-0073.pdf', type: 'Certificate', uploadedDate: '2 Jul 2026', uploadedBy: 'System', status: 'Verified', sizeLabel: '0.8 MB' },
  { id: 'CDOC-064', claimId: 'CLM-2024-0885', name: 'Claims Committee Approval Memo (£1,850 Net).pdf', type: 'Report', uploadedDate: '20 Jul 2026', uploadedBy: 'Omar Hassan', status: 'Verified', sizeLabel: '0.5 MB' },

  // CLM-2024-0884 (Fatima Al-Rashid - Fire Damage - Paid)
  { id: 'CDOC-070', claimId: 'CLM-2024-0884', name: 'Extractor Fan Short Circuit Scorching.jpg', type: 'Photo', uploadedDate: '29 Jun 2026', uploadedBy: 'Fatima Al-Rashid', status: 'Verified', sizeLabel: '3.6 MB' },
  { id: 'CDOC-071', claimId: 'CLM-2024-0884', name: 'NICEIC Electrical Safety Cert.pdf', type: 'Report', uploadedDate: '1 Jul 2026', uploadedBy: 'Fatima Al-Rashid', status: 'Verified', sizeLabel: '1.5 MB' },
  { id: 'CDOC-072', claimId: 'CLM-2024-0884', name: 'Kitchen Wall De-smoke & Repainting Invoice.pdf', type: 'Evidence', uploadedDate: '3 Jul 2026', uploadedBy: 'Fatima Al-Rashid', status: 'Verified', sizeLabel: '0.9 MB' },
  { id: 'CDOC-073', claimId: 'CLM-2024-0884', name: 'Certificate TK-2024-0042.pdf', type: 'Certificate', uploadedDate: '29 Jun 2026', uploadedBy: 'System', status: 'Verified', sizeLabel: '0.8 MB' },
  { id: 'CDOC-074', claimId: 'CLM-2024-0884', name: 'Treasury Payout Confirmation (£1,600).pdf', type: 'Report', uploadedDate: '12 Jul 2026', uploadedBy: 'Amira Siddiqui', status: 'Verified', sizeLabel: '0.4 MB' },
];

/* ─── Claim Notes ────────────────────────────────────────────────────────── */
export const CLAIM_NOTES: ClaimNote[] = [
  // CLM-2024-0891 (Fatima Al-Rashid - Storm - Under Review)
  {
    id: 'NOTE-001',
    claimId: 'CLM-2024-0891',
    authorId: 'U-HAND-001',
    authorName: 'Omar Hassan',
    authorInitials: 'OH',
    authorRole: 'Senior Claims Handler',
    authorGender: 'male',
    text: 'Property inspection confirmed roof damage consistent with storm on 16–17 Jul. Estimate aligns with claimed amount (£4,200). Awaiting independent surveyor visit report before final approval signoff.',
    isInternal: true,
    createdAt: '20 Jul 2026, 11:42',
  },
  {
    id: 'NOTE-002',
    claimId: 'CLM-2024-0891',
    authorId: 'U-PART-001',
    authorName: 'Fatima Al-Rashid',
    authorInitials: 'FA',
    authorRole: 'Participant',
    authorGender: 'female',
    text: 'Assalamu Alaikum Omar, I have uploaded the roofing contractor estimate and 8 high-resolution photos of the dislodged slates and loft joists. Please let me know when the assessor will arrive.',
    isInternal: false,
    createdAt: '19 Jul 2026, 14:10',
  },
  {
    id: 'NOTE-003',
    claimId: 'CLM-2024-0891',
    authorId: 'U-HAND-001',
    authorName: 'Omar Hassan',
    authorInitials: 'OH',
    authorRole: 'Senior Claims Handler',
    authorGender: 'male',
    text: 'Walaikum Assalam Fatima. All photos received clearly. We have scheduled Dave Miller from Independent Assessors Ltd for Friday 25 July at 10:00 AM to inspect the loft.',
    isInternal: false,
    createdAt: '20 Jul 2026, 09:30',
  },
  {
    id: 'NOTE-004',
    claimId: 'CLM-2024-0891',
    authorId: 'SYSTEM',
    authorName: 'System',
    authorInitials: 'SY',
    authorRole: 'Automated Service',
    text: 'All required documentation received. Claim progressed to Under Review status. SLA target: 5 business days.',
    isInternal: false,
    createdAt: '19 Jul 2026, 09:15',
  },

  // CLM-2024-0890 (Hassan Mahmoud - Escape of Water - Approved)
  {
    id: 'NOTE-010',
    claimId: 'CLM-2024-0890',
    authorId: 'U-HAND-001',
    authorName: 'Omar Hassan',
    authorInitials: 'OH',
    authorRole: 'Senior Claims Handler',
    authorGender: 'male',
    text: 'Verified plumber invoice and replacement quote for water-damaged floor and skirting. Gross repair of £1,850 assessed. After applying £300 certificate excess, net settlement of £1,550 approved.',
    isInternal: true,
    createdAt: '21 Jul 2026, 10:15',
  },
  {
    id: 'NOTE-011',
    claimId: 'CLM-2024-0890',
    authorId: 'U-HAND-001',
    authorName: 'Omar Hassan',
    authorInitials: 'OH',
    authorRole: 'Senior Claims Handler',
    authorGender: 'male',
    text: 'Hello Hassan, your claim has been assessed at £1,850.00 gross loss. Applying your £300 certificate excess, your net settlement of £1,550.00 is approved in full. Our finance team will execute the BACS transfer during the upcoming treasury batch.',
    isInternal: false,
    createdAt: '21 Jul 2026, 10:45',
  },
  {
    id: 'NOTE-012',
    claimId: 'CLM-2024-0890',
    authorId: 'P-0087',
    authorName: 'Hassan Mahmoud',
    authorInitials: 'HM',
    authorRole: 'Participant',
    authorGender: 'male',
    text: 'JazakAllah Khair Omar. I truly appreciate the rapid handling. The plumber has already completed the primary isolation valve repair.',
    isInternal: false,
    createdAt: '21 Jul 2026, 12:20',
  },
  {
    id: 'NOTE-013',
    claimId: 'CLM-2024-0890',
    authorId: 'U-FIN-001',
    authorName: 'Amira Siddiqui',
    authorInitials: 'AS',
    authorRole: 'Finance Officer',
    authorGender: 'female',
    text: 'Disbursement file queued for batch release on Thursday. Remittance advice will be posted automatically.',
    isInternal: true,
    createdAt: '21 Jul 2026, 15:00',
  },

  // CLM-2024-0889 (Aisha Okonkwo - Accidental Damage - Paid)
  {
    id: 'NOTE-020',
    claimId: 'CLM-2024-0889',
    authorId: 'U-HAND-001',
    authorName: 'Omar Hassan',
    authorInitials: 'OH',
    authorRole: 'Senior Claims Handler',
    authorGender: 'male',
    text: 'Patio double-glazing unit shattered by football impact. Inspected supplier receipt (£380.00). Approved as compliant with accidental damage clause.',
    isInternal: true,
    createdAt: '18 Jul 2026, 09:30',
  },
  {
    id: 'NOTE-021',
    claimId: 'CLM-2024-0889',
    authorId: 'U-FIN-001',
    authorName: 'Amira Siddiqui',
    authorInitials: 'AS',
    authorRole: 'Finance Officer',
    authorGender: 'female',
    text: 'Payment of £380.00 executed via BACS to Aisha Okonkwo. Bank ref: PYMNT-CLM-0889. Pool claims ledger reconciled.',
    isInternal: true,
    createdAt: '21 Jul 2026, 11:20',
  },
  {
    id: 'NOTE-022',
    claimId: 'CLM-2024-0889',
    authorId: 'P-0112',
    authorName: 'Aisha Okonkwo',
    authorInitials: 'AO',
    authorRole: 'Participant',
    authorGender: 'female',
    text: 'Hello Takaful team, I confirm receipt of the £380 payment in my Barclays account today. Thank you so much for the swift help!',
    isInternal: false,
    createdAt: '21 Jul 2026, 14:05',
  },
  {
    id: 'NOTE-023',
    claimId: 'CLM-2024-0889',
    authorId: 'SYSTEM',
    authorName: 'System',
    authorInitials: 'SY',
    authorRole: 'Automated Service',
    text: 'Claim CLM-2024-0889 marked as Paid and settled. Case closed in 6 days (Target: 10 days).',
    isInternal: false,
    createdAt: '21 Jul 2026, 16:00',
  },

  // CLM-2024-0888 (Fatima Al-Rashid - Theft Damage - Rejected)
  {
    id: 'NOTE-030',
    claimId: 'CLM-2024-0888',
    authorId: 'U-HAND-001',
    authorName: 'Omar Hassan',
    authorInitials: 'OH',
    authorRole: 'Senior Claims Handler',
    authorGender: 'male',
    text: 'Assessed attempted break-in damage. Locksmith quote is £250.00. Certificate TK-2024-0042 carries a mandatory £300 excess under Clause 4.2. Therefore, claim must be rejected as it falls below the minimum policy excess.',
    isInternal: true,
    createdAt: '17 Jul 2026, 14:15',
  },
  {
    id: 'NOTE-031',
    claimId: 'CLM-2024-0888',
    authorId: 'U-HAND-001',
    authorName: 'Omar Hassan',
    authorInitials: 'OH',
    authorRole: 'Senior Claims Handler',
    authorGender: 'male',
    text: 'Dear Fatima, thank you for providing the police crime log and locksmith repair quote. Regrettably, because the total repair cost of £250.00 is lower than your certificate policy excess of £300.00, we cannot disburse funds from the participant pool. You may review the formal rejection letter in your documents tab or submit an appeal with additional receipts.',
    isInternal: false,
    createdAt: '18 Jul 2026, 10:00',
  },
  {
    id: 'NOTE-032',
    claimId: 'CLM-2024-0888',
    authorId: 'P-0042',
    authorName: 'Fatima Al-Rashid',
    authorInitials: 'FA',
    authorRole: 'Participant',
    authorGender: 'female',
    text: 'Assalamu Alaikum Omar, understood completely regarding the £300 excess policy. I appreciate your quick review and clear guidance. I have paid the locksmith directly.',
    isInternal: false,
    createdAt: '18 Jul 2026, 11:30',
  },
  {
    id: 'NOTE-033',
    claimId: 'CLM-2024-0888',
    authorId: 'SYSTEM',
    authorName: 'System',
    authorInitials: 'SY',
    authorRole: 'Automated Service',
    text: 'Claim status set to Rejected. Clause 4.2 (Excess & Deductibles) applied. Participant notified.',
    isInternal: false,
    createdAt: '18 Jul 2026, 10:05',
  },

  // CLM-2024-0887 (Maryam Patel - Theft - Approved)
  {
    id: 'NOTE-040',
    claimId: 'CLM-2024-0887',
    authorId: 'U-HAND-001',
    authorName: 'Omar Hassan',
    authorInitials: 'OH',
    authorRole: 'Senior Claims Handler',
    authorGender: 'male',
    text: 'Bicycle theft from locked shed. Police reference verified with Leicestershire Constabulary. Halfords receipt confirms £650 gross value. Standard £300 compulsory excess deducted, resulting in £350 net settlement approved.',
    isInternal: true,
    createdAt: '19 Jul 2026, 11:20',
  },
  {
    id: 'NOTE-041',
    claimId: 'CLM-2024-0887',
    authorId: 'U-HAND-001',
    authorName: 'Omar Hassan',
    authorInitials: 'OH',
    authorRole: 'Senior Claims Handler',
    authorGender: 'male',
    text: 'Salam Maryam, your bicycle theft claim has been approved at £650.00 gross loss. After your £300 certificate excess, net settlement of £350.00 has been submitted to Treasury for BACS disbursement.',
    isInternal: false,
    createdAt: '19 Jul 2026, 11:50',
  },
  {
    id: 'NOTE-042',
    claimId: 'CLM-2024-0887',
    authorId: 'P-0098',
    authorName: 'Maryam Patel',
    authorInitials: 'MP',
    authorRole: 'Participant',
    authorGender: 'female',
    text: 'Thank you so much Omar! That is a huge relief. Please let me know once finance authorizes the payout.',
    isInternal: false,
    createdAt: '19 Jul 2026, 13:15',
  },

  // CLM-2024-0886 (Ibrahim Al-Sayed - Subsidence - Awaiting Information)
  {
    id: 'NOTE-050',
    claimId: 'CLM-2024-0886',
    authorId: 'U-HAND-001',
    authorName: 'Omar Hassan',
    authorInitials: 'OH',
    authorRole: 'Senior Claims Handler',
    authorGender: 'male',
    text: 'Critical subsidence claim (£12,400). Cracking to rear external wall requires full chartered structural engineer borehole and foundation movement report before pool risk release.',
    isInternal: true,
    createdAt: '14 Jul 2026, 16:30',
  },
  {
    id: 'NOTE-051',
    claimId: 'CLM-2024-0886',
    authorId: 'U-HAND-001',
    authorName: 'Omar Hassan',
    authorInitials: 'OH',
    authorRole: 'Senior Claims Handler',
    authorGender: 'male',
    text: 'Salam Ibrahim, we require a formal structural engineer survey assessing soil moisture and foundation displacement. Please let us know when your engineer is booked.',
    isInternal: false,
    createdAt: '15 Jul 2026, 09:40',
  },
  {
    id: 'NOTE-052',
    claimId: 'CLM-2024-0886',
    authorId: 'P-0055',
    authorName: 'Ibrahim Al-Sayed',
    authorInitials: 'IA',
    authorRole: 'Participant',
    authorGender: 'male',
    text: 'Walaikum Salam Omar. The chartered surveyor from Bristol Geotechnical is scheduled for Tuesday 23 July at 11am. I will upload the full report directly to the portal as soon as I receive the PDF.',
    isInternal: false,
    createdAt: '15 Jul 2026, 14:20',
  },

  // CLM-2024-0885 (Zahra Hussein - Water Leak - Approved)
  {
    id: 'NOTE-060',
    claimId: 'CLM-2024-0885',
    authorId: 'U-HAND-001',
    authorName: 'Omar Hassan',
    authorInitials: 'OH',
    authorRole: 'Senior Claims Handler',
    authorGender: 'male',
    text: 'Plumber invoices and drying certificate verified. Total remediation expense is £2,150 gross. Applying £300 certificate excess, net settlement of £1,850 approved for payment.',
    isInternal: true,
    createdAt: '20 Jul 2026, 10:00',
  },
  {
    id: 'NOTE-061',
    claimId: 'CLM-2024-0885',
    authorId: 'U-HAND-001',
    authorName: 'Omar Hassan',
    authorInitials: 'OH',
    authorRole: 'Senior Claims Handler',
    authorGender: 'male',
    text: 'Hello Zahra, your water leak repair claim has been assessed at £2,150.00 gross loss. Applying your £300 certificate excess, net settlement of £1,850.00 has been approved. Remittance will be processed to your registered account.',
    isInternal: false,
    createdAt: '20 Jul 2026, 10:30',
  },
  {
    id: 'NOTE-062',
    claimId: 'CLM-2024-0885',
    authorId: 'P-0073',
    authorName: 'Zahra Hussein',
    authorInitials: 'ZH',
    authorRole: 'Participant',
    authorGender: 'female',
    text: 'Thank you Omar and the Takaful team for such professional support! Truly grateful for the prompt handling.',
    isInternal: false,
    createdAt: '20 Jul 2026, 13:00',
  },

  // CLM-2024-0884 (Fatima Al-Rashid - Fire Damage - Paid)
  {
    id: 'NOTE-070',
    claimId: 'CLM-2024-0884',
    authorId: 'U-HAND-001',
    authorName: 'Omar Hassan',
    authorInitials: 'OH',
    authorRole: 'Senior Claims Handler',
    authorGender: 'male',
    text: 'NICEIC certified inspection confirmed accidental short circuit in extractor fan. Kitchen cleaning and repainting invoice £1,600 verified. Net settlement of £1,300 (£1,600 − £300 excess) authorized and closed.',
    isInternal: true,
    createdAt: '11 Jul 2026, 15:40',
  },
  {
    id: 'NOTE-071',
    claimId: 'CLM-2024-0884',
    authorId: 'U-FIN-001',
    authorName: 'Amira Siddiqui',
    authorInitials: 'AS',
    authorRole: 'Finance Officer',
    authorGender: 'female',
    text: 'Net settlement payment of £1,300.00 released to Fatima Al-Rashid via BACS (BACS-TK-2026-0884). Reconciled in general claims reserve account.',
    isInternal: true,
    createdAt: '12 Jul 2026, 10:15',
  },
  {
    id: 'NOTE-072',
    claimId: 'CLM-2024-0884',
    authorId: 'U-PART-001',
    authorName: 'Fatima Al-Rashid',
    authorInitials: 'FA',
    authorRole: 'Participant',
    authorGender: 'female',
    text: 'Net funds of £1,300 were received safely and the kitchen has been repainted. Thank you so much for the Takaful support during this stressful event.',
    isInternal: false,
    createdAt: '12 Jul 2026, 14:30',
  },
  {
    id: 'NOTE-073',
    claimId: 'CLM-2024-0884',
    authorId: 'SYSTEM',
    authorName: 'System',
    authorInitials: 'SY',
    authorRole: 'Automated Service',
    text: 'Claim CLM-2024-0884 settled and closed. Remittance advice archived.',
    isInternal: false,
    createdAt: '12 Jul 2026, 10:20',
  },
];

/* ─── Transactions ───────────────────────────────────────────────────────── */
export const TRANSACTIONS: Transaction[] = [
  { id: 'TXN-8812', date: '1 Jul 2026', type: 'Contribution', participantId: 'P-0042', participantName: 'Fatima Al-Rashid', certificateId: 'TK-2024-0042', amount: 38.50, direction: 'Inflow', status: 'Reconciled', reference: 'DD-2024-0042-JUL', reconciled: true },
  { id: 'TXN-8811', date: '1 Jul 2026', type: 'Contribution', participantId: 'P-0087', participantName: 'Hassan Mahmoud', certificateId: 'TK-2024-0087', amount: 24.20, direction: 'Inflow', status: 'Reconciled', reference: 'DD-2024-0087-JUL', reconciled: true },
  { id: 'TXN-8810', date: '1 Jul 2026', type: 'Contribution', participantId: 'P-0112', participantName: 'Aisha Okonkwo', certificateId: 'TK-2024-0112', amount: 52.80, direction: 'Inflow', status: 'Reconciled', reference: 'DD-2024-0112-JUL', reconciled: true },
  { id: 'TXN-PAY-001', date: '21 Jul 2026', type: 'ClaimPayment', participantId: 'P-0112', participantName: 'Aisha Okonkwo', claimId: 'CLM-2024-0889', amount: 380, direction: 'Outflow', status: 'Completed', reference: 'BACS-TK-2026-0889', reconciled: true },
  { id: 'TXN-PAY-002', date: '12 Jul 2026', type: 'ClaimPayment', participantId: 'P-0042', participantName: 'Fatima Al-Rashid', claimId: 'CLM-2024-0884', amount: 1300, direction: 'Outflow', status: 'Completed', reference: 'BACS-TK-2026-0884', reconciled: true },
  { id: 'TXN-FEE-JUL', date: '1 Jul 2026', type: 'WakalaFee', amount: 4912, direction: 'Outflow', status: 'Completed', reference: 'WAKALA-JUL-2026', reconciled: true },
  { id: 'TXN-8808', date: '1 Jul 2026', type: 'Contribution', participantId: 'P-0098', participantName: 'Maryam Patel', certificateId: 'TK-2024-0098', amount: 18.90, direction: 'Inflow', status: 'Failed', reference: 'DD-2024-0098-JUL', reconciled: false },
];

/* ─── Pool State ─────────────────────────────────────────────────────────── */
export const POOL: Pool = {
  balance: 482150,
  participantFundPct: 78,
  claimsReservePct: 14,
  wakalaFeePct: 8,
  totalContributions: 618400,
  totalClaimsPaid: 92800,
  totalWakalaFees: 49472,
  claimsReserve: 43450,
  periodLabel: 'Jul 2026',
};

/* ─── Chart / Trend Data ─────────────────────────────────────────────────── */
export const CONTRIBUTION_TREND = [
  { month: 'Jan', total: 42800, collected: 41600, failed: 1200 },
  { month: 'Feb', total: 46200, collected: 45100, failed: 1100 },
  { month: 'Mar', total: 51000, collected: 50200, failed: 800 },
  { month: 'Apr', total: 49500, collected: 48800, failed: 700 },
  { month: 'May', total: 53800, collected: 52900, failed: 900 },
  { month: 'Jun', total: 58200, collected: 56900, failed: 1300 },
  { month: 'Jul', total: 61400, collected: 59600, failed: 1800 },
];

export const CLAIMS_TREND = [
  { month: 'Jan', count: 8, value: 12400 },
  { month: 'Feb', count: 6, value: 9800 },
  { month: 'Mar', count: 11, value: 14200 },
  { month: 'Apr', count: 9, value: 11100 },
  { month: 'May', count: 13, value: 16500 },
  { month: 'Jun', count: 10, value: 13200 },
  { month: 'Jul', count: 14, value: 18900 },
];

export const PARTICIPANT_GROWTH = [
  { month: 'Jan', participants: 1148 },
  { month: 'Feb', participants: 1179 },
  { month: 'Mar', participants: 1205 },
  { month: 'Apr', participants: 1218 },
  { month: 'May', participants: 1240 },
  { month: 'Jun', participants: 1262 },
  { month: 'Jul', participants: 1284 },
];

export const POOL_HISTORY = [
  { month: 'Jan', balance: 340000 },
  { month: 'Feb', balance: 370000 },
  { month: 'Mar', balance: 406000 },
  { month: 'Apr', balance: 444000 },
  { month: 'May', balance: 478000 },
  { month: 'Jun', balance: 463000 },
  { month: 'Jul', balance: 482150 },
];

/* ─── Approved claims awaiting payment (Finance view) ───────────────────── */
export const CLAIMS_AWAITING_PAYMENT = CLAIMS.filter(
  (c) => c.status === 'Approved' && c.amountApproved !== undefined
);
