import {
  FileText, CheckCircle2, AlertTriangle, Shield,
  CreditCard, Users, Info, XCircle, MessageSquare,
  type LucideIcon,
} from 'lucide-react';

export interface NotificationItem {
  id: string;
  type: 'claim' | 'certificate' | 'payment' | 'document' | 'participant' | 'pool';
  icon: LucideIcon;
  color: string;
  title: string;
  body: string;
  time: string;
  read: boolean;
  link: string;
  senderName?: string;
  senderGender?: 'male' | 'female';
}

/* ─── Handler / Management / Finance Notifications ────────────────────────── */
export const HANDLER_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'N-001',
    type: 'claim',
    icon: FileText,
    color: '#3b82f6',
    title: 'New claim submitted',
    body: 'Hassan Mahmoud submitted claim CLM-2024-0890 for £1,850 (Contents — Escape of Water).',
    time: '2 minutes ago',
    read: false,
    link: '/dashboard/claims/CLM-2024-0890',
    senderName: 'Hassan Mahmoud',
    senderGender: 'male',
  },
  {
    id: 'N-002',
    type: 'claim',
    icon: CheckCircle2,
    color: '#00c685',
    title: 'Claim approved & sent to finance',
    body: 'Claim CLM-2024-0889 for Aisha Okonkwo (Accidental Damage, £380) has been approved and forwarded to Treasury for payment.',
    time: '18 minutes ago',
    read: false,
    link: '/dashboard/claims/CLM-2024-0889',
    senderName: 'Omar Hassan',
    senderGender: 'male',
  },
  {
    id: 'N-003',
    type: 'document',
    icon: AlertTriangle,
    color: '#f59e0b',
    title: 'Documents still outstanding',
    body: 'Claim CLM-2024-0886 (Ibrahim Al-Sayed – Subsidence, £12,400) requires the structural engineer survey report. Chased on 15 Jul.',
    time: '1 hour ago',
    read: false,
    link: '/dashboard/claims/CLM-2024-0886',
    senderName: 'System',
    senderGender: 'male',
  },
  {
    id: 'N-004',
    type: 'certificate',
    icon: Shield,
    color: '#8b5cf6',
    title: 'Certificate expiring soon',
    body: 'Certificate TK-2024-0098 (Maryam Patel) expires in 14 days on 12 Aug 2026. Renewal action required.',
    time: '2 hours ago',
    read: false,
    link: '/dashboard/certificates',
    senderName: 'System',
    senderGender: 'male',
  },
  {
    id: 'N-005',
    type: 'payment',
    icon: CreditCard,
    color: '#ef4444',
    title: 'Direct debit failed',
    body: 'Contribution collection failed for Maryam Patel (TK-2024-0098). Amount: £18.90. Retry scheduled.',
    time: '4 hours ago',
    read: false,
    link: '/dashboard/contributions',
    senderName: 'System',
    senderGender: 'male',
  },
  {
    id: 'N-006',
    type: 'participant',
    icon: Users,
    color: '#ec4899',
    title: 'New applications received',
    body: '3 new participant applications are pending review. 2 require identity verification.',
    time: '6 hours ago',
    read: true,
    link: '/dashboard/participants',
    senderName: 'System',
    senderGender: 'male',
  },
  {
    id: 'N-007',
    type: 'pool',
    icon: Info,
    color: '#00c685',
    title: 'Pool monthly summary',
    body: 'July 2026 pool summary: £61,400 collected, £18,900 in claims. Pool balance: £482,150. Full report available.',
    time: '1 day ago',
    read: true,
    link: '/dashboard/pool',
    senderName: 'System',
    senderGender: 'male',
  },
  {
    id: 'N-008',
    type: 'claim',
    icon: FileText,
    color: '#3b82f6',
    title: 'Assessor report received',
    body: 'Assessor report for CLM-2024-0891 (Fatima Al-Rashid – Storm damage, £4,200) has been received and is ready for review.',
    time: '1 day ago',
    read: true,
    link: '/dashboard/claims/CLM-2024-0891',
    senderName: 'System',
    senderGender: 'male',
  },
  {
    id: 'N-009',
    type: 'payment',
    icon: CheckCircle2,
    color: '#00c685',
    title: 'Payment released by finance',
    body: 'Payment of £1,600 for claim CLM-2024-0884 (Fatima Al-Rashid – Fire Damage) has been transferred to participant account. BACS ref: PYMNT-CLM-0884.',
    time: '2 days ago',
    read: true,
    link: '/dashboard/claims/CLM-2024-0884',
    senderName: 'Amira Siddiqui',
    senderGender: 'female',
  },
];

/* ─── Participant Notifications (role-specific, Fatima P-0042) ─────────────── */
export const PARTICIPANT_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'PN-001',
    type: 'claim',
    icon: XCircle,
    color: '#ef4444',
    title: 'Claim decision: Rejected',
    body: 'Your claim CLM-2024-0888 (Attempted Break-In — Front Door Lock, £250) has been rejected. Repair cost falls below £300 policy excess.',
    time: '18 Jul 2026',
    read: false,
    link: '/portal/claims/CLM-2024-0888',
    senderName: 'Omar Hassan',
    senderGender: 'male',
  },
  {
    id: 'PN-002',
    type: 'payment',
    icon: CheckCircle2,
    color: '#00c685',
    title: 'Payment confirmed — £1,600 received',
    body: 'Your settlement payment of £1,600.00 for fire damage claim CLM-2024-0884 has been processed and deposited to your bank account.',
    time: '12 Jul 2026',
    read: false,
    link: '/portal/claims/CLM-2024-0884',
    senderName: 'Amira Siddiqui',
    senderGender: 'female',
  },
  {
    id: 'PN-003',
    type: 'claim',
    icon: AlertTriangle,
    color: '#f59e0b',
    title: 'Assessor visit scheduled',
    body: 'For storm damage claim CLM-2024-0891, an independent assessor (Dave Miller) has been booked for Friday 25 July at 10:00 AM.',
    time: '20 Jul 2026',
    read: false,
    link: '/portal/claims/CLM-2024-0891',
    senderName: 'Omar Hassan',
    senderGender: 'male',
  },
  {
    id: 'PN-004',
    type: 'claim',
    icon: MessageSquare,
    color: '#3b82f6',
    title: 'New message from your handler',
    body: 'Omar Hassan: "All photos received clearly. We have scheduled Dave Miller for Friday 25 July at 10:00 AM..."',
    time: '20 Jul 2026',
    read: true,
    link: '/portal/claims/CLM-2024-0891',
    senderName: 'Omar Hassan',
    senderGender: 'male',
  },
  {
    id: 'PN-005',
    type: 'document',
    icon: FileText,
    color: '#8b5cf6',
    title: 'Schedule of loss uploaded',
    body: 'Loss adjuster document Schedule_of_Loss_CLM-0891.pdf has been uploaded to your claim file.',
    time: '21 Jul 2026',
    read: true,
    link: '/portal/documents',
    senderName: 'System',
    senderGender: 'male',
  },
  {
    id: 'PN-006',
    type: 'certificate',
    icon: Shield,
    color: '#00c685',
    title: 'Certificate TK-2024-0042 is active',
    body: 'Your Takaful Buildings Certificate is active and covers storm, fire, flood, subsidence, and escape of water. Renews 15 Jan 2027.',
    time: '15 Jan 2026',
    read: true,
    link: '/portal/my-cover',
    senderName: 'System',
    senderGender: 'male',
  },
];
